backend:
  name: pingping-frontend
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'quote'
    label: 'Quote'
    format: 'json'
    folder: 'content/blog'
    create: true
    slug: 'quote-{{id}}'
    editor:
      preview: false
    fields:
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Quote', name: 'quote', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Person', name: 'person', widget: 'string' }